### PR TITLE
[fix] #275

### LINKED ISSUE #275: Build failure on sethrfore/r-srf/r version 4.0.3 (Mac OS X)
`R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"` — Installed [like this](https://blog.theforce.top/2019/06/20/install-r-with-all-capabilities-and-openblas-openmp-on-macos-by-homebrew/)

```
> install.packages("ggplot2")
```

[snip...]

```
clang-11: warning: argument unused during compilation: '-L/usr/local/opt/llvm/lib' [-Wunused-command-line-argument]
unix/processx.c:46:28: error: 'TARGET_OS_IPHONE' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if defined(__APPLE__) && !TARGET_OS_IPHONE
```

### PR DESCRIPTION
**Pull request by domq**
Be sure to `#include <TargetConditionals.h>` before using `TARGET_OS_IPHONE`, as seen [here](https://stackoverflow.com/a/11146573/435004)

Fixes #275

### CODE REVIEW

**Comment by domq** [comment]
image

💡 Of course I [removed my `-DTARGET_OS_IPHONE=0`](https://github.com/r-lib/processx/issues/275#issuecomment-713832957) prior to recompiling ☺

**Comment by gaborcsardi** [comment]
I would be very surprised if processx worked on iOS, so I think we can just remove that flag instead?

**Comment by domq** [comment]
> Thanks! I would be very surprised if processx worked on iOS, so I think we can just remove that flag instead?

Done, PTAL

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
